<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\GitHubBackup.Core\GitHubBackup.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="GitHubBackup.Infrastructure.Tests" />
    <InternalsVisibleTo Include="GitHubBackup.Infrastructure.IntegrationTests" />
  </ItemGroup>

</Project>
